Create "Linked site page changes" diagram and explanation
wmde/wikidata-wikibase-architecture pull request #32
Opened 2021-01-14 16:26 UTC by tzhelyazkova

Task: [T271949](https://phabricator.wikimedia.org/T271949)

2021-01-14 16:40 UTC, addshore requested changes
While looking at this diagram I can't help but think again that it could be nice to be able to show the external system that is being interacted with on the diagram.
I was thinking this while making the change related building block diagrams.

I think that would bring it closer to https://docs.arc42.org/section-5/
If we think thats the right direction then I would also go and change the other diagrams.

2021-01-14 16:40 UTC, addshore commented on systems/WikibaseClient/05-Building_Block_View.md
> +Responsible for notifying a repository that a page that is linked to by an entity has changed.
We should perhaps sync this line of description up with that which is currently in the table above.
I wonder if it should also only be in one of the 2 places.

2021-01-14 17:01 UTC, tzhelyazkova commented
> While looking at this diagram I can't help but think again that it could be nice to be able to show the external system that is being interacted with on the diagram.
> I was thinking this while making the change related building block diagrams.
> 
> I think that would bring it closer to https://docs.arc42.org/section-5/
> If we think thats the right direction then I would also go and change the other diagrams.

Do you mean, we should have `WikibaseRepo` drawn as an external system for all those block diagrams? Wouldn't that be the same thing already shown in the Whitebox Overall diagram on the same page?

2021-01-15 14:24 UTC, addshore commented
> > While looking at this diagram I can't help but think again that it could be nice to be able to show the external system that is being interacted with on the diagram.
> > I was thinking this while making the change related building block diagrams.
> > I think that would bring it closer to https://docs.arc42.org/section-5/
> > If we think thats the right direction then I would also go and change the other diagrams.
> 
> Do you mean, we should have `WikibaseRepo` drawn as an external system for all those block diagrams? Wouldn't that be the same thing already shown in the Whitebox Overall diagram on the same page?

In this situation yes perhaps, but in other situations the connections to external systems end up highlighting important things, and I feel we need to be consistent in the diagrams.

2021-01-15 14:28 UTC, addshore approved these changes
Looks good, I'm going to make a PR bringing the other diagram in this md file that I made more inline with the one added here as I prefer it.

2021-01-15 14:32 UTC, addshore commented
That PR is https://github.com/wmde/wikidata-wikibase-architecture/pull/35

2021-01-15 15:29 UTC, merged