Add high level building block diagram with mermaid JS
wmde/wikidata-wikibase-architecture pull request #5
Opened 2020-11-23 16:02 UTC by addshore

2020-11-24 10:01 UTC, Silvan-WMDE reviewed
One minor comment on the diagram.

I also tested the diagram generation locally and it works.

2020-11-24 10:13 UTC, tzhelyazkova commented on diagrams/README.md
> +```lang=sh
```suggestion
```sh
```

2020-11-24 10:13 UTC, tzhelyazkova commented on diagrams/README.md
> +```lang=sh
```suggestion
```sh
```

2020-11-24 10:13 UTC, tzhelyazkova commented on diagrams/README.md
> +```lang=sh
```suggestion
```sh
```

2020-11-24 10:13 UTC, tzhelyazkova commented on diagrams/README.md
> +```lang=sh
```suggestion
```sh
```

2020-11-24 18:56 UTC, addshore commented on diagrams/05-blocks-1.mmd
> +    user-query-->|Queries|query
Yes, as users can query the API directly, or they can use the UI

2020-11-24 19:37 UTC, addshore commented
Generally I'm happy with the direction this took for now.
I did look at investigating "watch" stuff a little bit but decided after a few mins it probably isn't worth it yet.
I think using mermaid will make sense and that probably won't change in the future?
We will probably end up using some generator that does more things in the future (I had a quick look at githubify which has built in mermaid support in markdown files for example)

2020-11-25 09:43 UTC, Silvan-WMDE requested changes

2020-11-25 09:43 UTC, Silvan-WMDE commented on diagrams/README.md
> +npm run buildd:diagrams
```suggestion
npm run build-docker:diagrams
```

2020-11-25 09:43 UTC, Silvan-WMDE commented on diagrams/package.json
> +    "buildd:diagrams" : "docker run --rm -it -v \"$PWD:/app\" $(docker build -t wikibase-architecture-diagrams -q .) npm run build:diagrams"
```suggestion
    "build-docker:diagrams" : "docker run --rm -it -v \"$PWD:/app\" $(docker build -t wikibase-architecture-diagrams -q .) npm run build:diagrams"
```

2020-11-25 14:41 UTC, tzhelyazkova approved these changes

2020-11-25 16:28 UTC, addshore commented
Regarding the diagram in general I feel that we should think about these points a bit and see if this is the approach that we want to take for documentation, or having something a bit more manual?
 - As much as manipulation can break a message, bad visuals can unintentionally spread confusion
- Entire systems can be built subtly wrong due to bad graphs or unclear but technically correct docs

Perhaps we end up with a mix of things like mermaid for sequence diagrams but some other tooling for these less structured diagrams.
I have to say that currently the concept board version of this seems a little more parsable to me.

2020-11-26 14:07 UTC, Silvan-WMDE commented
> I have to say that currently the concept board version of this seems a little more parsable to me.

I agree about the readability of the manually created one, but we should ensure to have an SVG version of it, which conceptboard doesn't offer as export, I think.

2020-11-26 14:07 UTC, Silvan-WMDE approved these changes

2020-11-27 10:35 UTC, merged