Add maintenance script to new Interwiki building block
wmde/wikidata-wikibase-architecture pull request #63
Opened 2021-01-26 12:56 UTC by Silvan-WMDE

This introduces a new "Interwiki" building block to the Client's
Overview diagram and adds a maintenance script to the corresponding
subsection.

The Interwiki building block is expected to be completed later.

Bug: [T272972](https://phabricator.wikimedia.org/T272972)

2021-01-26 15:11 UTC, addshore requested changes
I think the interwiki block within the client should also exist in the context and scope diagram?
This would connect to the Interwiki block in MediaWiki which is also not currently represented there.

2021-01-26 16:59 UTC, addshore commented
In systems/WikibaseClient/diagrams/05-building-blocks.drawio.svg this PR introduced an arrow going from Repo -> Interwiki, which in the long term may be correct, but isn't really represented by the current content of the docs (as we haven't finished client yet).
I feel that we should wait until we introduce that arrow with purpose and an idea of how the block works behind it, rather than assuming that repo probably directly interacts with this interwiki block.

This is already reflected in the context diagram, which doesn't have this connection.

2021-02-01 10:18 UTC, tzhelyazkova approved these changes

2021-02-01 11:39 UTC, addshore commented on systems/WikibaseClient/05-Building_Block_View.md
> +| [Interwiki](#interwiki)                                     | Client side interactions with Interwiki links                                    |
We say "WikibaseClient specific" above, but "Client side" here.
I believe these are meant to mean the same thing?

2021-02-01 11:39 UTC, addshore approved these changes

2021-02-01 11:39 UTC, addshore commented
Left 1 comment, but not blocking getting this merged on that.

2021-02-01 11:39 UTC, merged