Explain various users across diagrams
wmde/wikidata-wikibase-architecture pull request #78
Opened 2021-02-03 14:24 UTC by tzhelyazkova

Rename the generic User to Client Editor or Wikidata Editor or Repo Editor based on the context.
Add more stakeholders to the overview section in line with the overall whitebox diagram.

2021-02-03 15:11 UTC, addshore commented on systems/overview/01-Introduction_and_Goals.md
> +### Query User
User here but user below

2021-02-03 15:11 UTC, addshore approved these changes

2021-02-03 16:57 UTC, tzhelyazkova commented on systems/overview/01-Introduction_and_Goals.md
> +### Query User
```suggestion
### Query user
```

2021-02-04 14:40 UTC, Silvan-WMDE requested changes
While "User" may have been to general, I think the users in the diagrams may now be too specific:

The Client introduction mentions three stakeholders: Client editor, Wikimedia editor and Wikipedia editor - yet the new client diagrams only show the Client editor. Shouldn't they all show up somewhere?

In the Repo Introduction, there is the Repo editor and the Wikidata editor. I'm not even sure what the difference is between those two, but the diagrams don't show, either.

I also noticed that the tables below the context diagrams still describe the now renamed "User", both in Repo and Client. If the three different stakeholders have different roles in the diagram, maybe each of them deserves a separate row? If instead they all have essentially the same role, maybe it makes sense to stick with "User" in the "Neighbour" column (and the diagram), but then list the different stakeholders in the "Description" column and link to the corresponding Stakeholders section from there?

Interestingly, in the Overall building block diagram there's a "Wikidata Editor / Viewer" and a "Client Editor / Viewer", which I like and maybe that's a an elegant solution for the diagrams here, too. Unfortunately, in the Stakeholders section we don't even have a "Wikidata Viewer" or "Client Viewer". Maybe they should be added, if we have them in the diagram? Or rename them in the diagram instead?

2021-02-05 11:05 UTC, tzhelyazkova commented
@addshore @jakobw @Silvan-WMDE the overview diagram mentions Viewers but we don't have them defined as stakeholders anywhere.
Should we remove them from the diagram or add Readers/Viewers to the stakeholders section? If we decide to add them, which sections should we choose - client, repo or overview?

2021-02-05 11:38 UTC, Silvan-WMDE commented
I believe the "Viewers" are a big and important group of stakeholders and I think we should take some time to define and write down which viewer groups we actually have: Client Viewers? Repo Viewers? Or rather Wikipedia Viewers and Wikidata Viewers?

If others agree, we could make this a phabricator ticket.

2021-02-05 11:39 UTC, Silvan-WMDE approved these changes

2021-02-05 13:52 UTC, tzhelyazkova commented
> I believe the "Viewers" are a big and important group of stakeholders and I think we should take some time to define and write down which viewer groups we actually have: Client Viewers? Repo Viewers? Or rather Wikipedia Viewers and Wikidata Viewers?
> 
> If others agree, we could make this a phabricator ticket.

Filed [T273973](https://phabricator.wikimedia.org/T273973)

2021-02-05 13:52 UTC, merged